--- DDL -  lenguaje de definición de datos
--- CREACION DE TABLAS
CREATE TABLE TIPO_PRODUCTO
(id_tipo NUMBER(10) NOT NULL
, descripcion VARCHAR(100) NOT NULL
, CONSTRAINT TIPO_PRODUCTO_PK PRIMARY KEY(id_tipo));

CREATE TABLE PRODUCTO
(cod_producto NUMBER(10) NOT NULL
, descripcion VARCHAR(100) NOT NULL
, precio_unitario NUMBER(10) NOT NULL
, id_tipo NUMBER(10) NOT NULL
, CONSTRAINT PRODUCTO_PK PRIMARY KEY(cod_producto)
, CONSTRAINT PRODUCTO_TIPO_PRODUCTO_FK FOREIGN KEY(id_tipo) REFERENCES TIPO_PRODUCTO(id_tipo));
---como eliminar tablas
DROP TABLE BOLETA;
--------------------------------
CREATE TABLE BOLETA
(nro_boleta NUMBER(10) NOT NULL
,fecha DATE NOT NULL
,total NUMBER(10) NOT NULL
,CONSTRAINT BOLETA_PK PRIMARY KEY(nro_boleta));

CREATE TABLE DET_BOLETA
(nro_boleta NUMBER(10) NOT NULL
,cod_producto NUMBER(10) NOT NULL
,cantidad NUMBER(10) NOT NULL
,subtotal NUMBER(10) NOT NULL
,CONSTRAINT DET_BOLETA_PK PRIMARY KEY(nro_boleta,cod_producto)
,CONSTRAINT DET_BOLETA_BOLETA_FK FOREIGN KEY(nro_boleta) REFERENCES BOLETA(nro_boleta)
,CONSTRAINT DET_BOLETA_PRODUCTO_FK FOREIGN KEY(cod_producto) REFERENCES PRODUCTO(cod_producto));



